/* The goal of this project is to explore and demonstrate the internal mechanics of .NET Generics, specifically focusing on Type Variance (Covariance/Contravariance), IL representation, and the Runtime behavior difference between Value Types and Reference Types.

Technical Requirements
1. Implementation of Variance Scenarios
Create a demonstration suite that proves why certain generic assignments are allowed or forbidden:

Invariant Case: Create a scenario showing that List<T> does not allow conversion from List<Derived> to List<Base>. Write a comment explaining the "Type Corruption" risk (adding a different derived type).

Covariant Case (out): Demonstrate the usage of IEnumerable<out T>. Successfully assign a List<string> to an IEnumerable<object>.

Contravariant Case (in): Implement an Action<in T> scenario. Assign an Action<Animal> to an Action<Dog>.

Logic to prove: Explain why a method that can handle any Animal is perfectly safe to handle a Dog.

2. Performance & Memory Observation
Implement a generic class MetadataInspector<T>:

Method Inspect(): Use typeof(T) to print whether the type is a ValueType or a Class.

Static Constructor: Add a static constructor to MetadataInspector<T> that prints: "JIT compiled for: " + typeof(T).Name.

Execution: In Main, instantiate the class for int, double, string, and object.

Observation Goal: Notice how the static constructor behaves for different types.

3. IL Exploration (Manual Task)
Build the project in Release mode and provide a brief analysis (as comments in code) of the IL instructions:

Identify the use of !0 or !!0.

Explain the role of ldtoken.
*/

using System;
using System.Collections.Generic;

namespace GenericDeepDive.TypeSafety.Lab
{
    // --- Setup for Variance Scenarios ---
    public class Animal { public string Name { get; set; } }
    public class Dog : Animal { public void Bark() => Console.WriteLine("Woof!"); }
    public class Cat : Animal { public void Meow() => Console.WriteLine("Meow!"); }

    // --- Performance & Memory Observation ---
    public class MetadataInspector<T>
    {
        // The Static Constructor is the key to seeing JIT Specialization.
        // It runs once for every "unique" machine code version generated by the JIT.
        static MetadataInspector()
        {
            Console.WriteLine($"[JIT NOTIFICATION] New machine code generated for: {typeof(T).Name}");
        }

        public void Inspect()
        {
            var type = typeof(T);
            string category = type.IsValueType ? "Value Type (Struct)" : "Reference Type (Class)";
            Console.WriteLine($"[INSPECT] {type.Name} is a {category}");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("=== 1. VARIANCE SCENARIOS ===\n");

            // --- INVARIANT CASE ---
            List<Dog> dogs = new List<Dog> { new Dog { Name = "Rex" } };
            // List<Animal> animals = dogs; // COMPILER ERROR!
            /* WHY: If this were allowed, I could do: animals.Add(new Cat()); 
               But 'dogs' is a List of Dogs. Adding a Cat would corrupt the list's type integrity.
               This is why Classes in C# are Invariant.
            */
            Console.WriteLine("[-] List<T> is Invariant: Prevents adding a Cat to a List of Dogs.");

            // --- COVARIANT CASE (out) ---
            // IEnumerable is defined as IEnumerable<out T>
            IEnumerable<Dog> dogRef = new List<Dog> { new Dog { Name = "Buddy" } };
            IEnumerable<Animal> animalRef = dogRef; // SUCCESS!
            /*
               WHY: 'out' means T only comes OUT of the object (GetEnumerator).
               Every Dog is an Animal, so it's safe to treat a stream of Dogs as a stream of Animals.
            */
            Console.WriteLine("[+] IEnumerable<out T> is Covariant: Safe to read Dogs as Animals.");

            // --- CONTRAVARIANT CASE (in) ---
            // Action is defined as Action<in T>
            Action<Animal> feedAnimal = (a) => Console.WriteLine($"Feeding animal: {a.Name}");
            Action<Dog> feedDog = feedAnimal; // SUCCESS!
            /*
               LOGIC: 'in' means T only goes INTO the method.
               If a method knows how to feed ANY Animal, it certainly knows how to feed a Dog.
               The method only expects Animal properties; a Dog satisfies that requirement.
            */
            Console.WriteLine("[+] Action<in T> is Contravariant: A general handler can serve a specific type.");


            Console.WriteLine("\n=== 2. PERFORMANCE & JIT OBSERVATION ===\n");

            // Value Types: JIT creates unique copies (Specialization)
            var intInspector = new MetadataInspector<int>();
            intInspector.Inspect();

            var doubleInspector = new MetadataInspector<double>();
            doubleInspector.Inspect();

            // Reference Types: JIT shares code (Canonical Representation)
            // Watch the logs: Static constructor might behave differently for Ref Types!
            var stringInspector = new MetadataInspector<string>();
            stringInspector.Inspect();

            var objectInspector = new MetadataInspector<object>();
            objectInspector.Inspect();

            /*
               OBSERVATION:
               For Value Types (int, double), you see the JIT log twice.
               For Reference Types (string, object), the JIT often shares the same 
               internal "canonical" implementation because pointers are always the same size.
            */
        }
    }
}